'''
Kevin Bohinski
bohinsk1@tcnj.edu
2015-3-2

Problem-Solving-Practice
projectEuler
prob2.py
Copyright (c) 2015 Kevin Bohinski. All rights reserved.
'''

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''

curr = 2
last = 1
temp = 0
i = 3
sum = 0

while (curr < 4000000):
    if (i == 3):
        sum = sum + curr
        i = 0
    temp = curr
    curr = curr + last
    last = temp
    i += 1

print(sum)